### ISSUE TITLE
Wrong command - profile: 'default_0RPM_ON_DONTMODIFY' not found

### ISSUE THREAD

**Issue by SgtBreadStick** [hoffr/RadeonClockEnforcer#3]
I've been trying to use RadeonClockEnforcer but unfortunately im having issues launching it because of the following errors.

![2021-02-14_20-59-26](https://user-images.githubusercontent.com/21985403/107888936-929aba00-6f07-11eb-96fc-5da70c7014b4.png)
![2021-02-14_20-59-29](https://user-images.githubusercontent.com/21985403/107888937-929aba00-6f07-11eb-91a1-c4751678f4a4.png)

I'm currently using a Radeon RX 5700 XT.
Is there a way to solve this issue?

**Comment by hoffor** [comment]
Could I see the contents of your `\RadeonClockEnforcer\OverdriveNTool.ini`? Seems that the 0RPM profile might not have been created for some reason, need to confirm

**Comment by SgtBreadStick** [comment]
Here you go [https://pastebin.com/FkQkMzSR](https://pastebin.com/FkQkMzSR)

**Comment by SgtBreadStick** [comment]
I just looked in the file and changed the "profile_0" line "Fan_ZeroRPM" to 0 and it created a 0RPM profile. 
Unfortunately it still causes the above error [https://pastebin.com/8RXgqnuW](https://pastebin.com/8RXgqnuW)

**Comment by hoffor** [comment]
@SgtBreadStick Go ahead and reset the .ini back to what it was and the new release in a minute should fix
